### ISSUE TITLE
Circuitpython

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit-APDS9960-Breakout-PCB#1]
Hi there.

Is there a plan to make a circuitpython library for this amazing sensor?

Best regards,
Pascal

**Comment by ladyada** [comment]
nope - we don't have it done yet! we'll make a new repo when we do :)

**Comment by tannewt** [comment]
I made an issue in the adafruit/circuitpython repo to track this: https://github.com/adafruit/circuitpython/issues/411
